create table WORD (
    KOREAN VARCHAR2(100),
    ENGLISH VARCHAR2(100));
    
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('고양이','cat');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('개','dog');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('사자','lion');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('호랑이','tiger');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('고래','whale');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('코알라','koala');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('캥거루','kangaroo');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('고슴도치','gedgehog');
INSERT INTO WORD(KOREAN,ENGLISH) VALUES ('여우','fox');


commit;


SELECT * FROM WORD;
