CREATE TABLE WMEMBER (
	NUM NUMBER PRIMARY KEY,
	NAME VARCHAR2(50),
	USERID VARCHAR2(50),
	PWD VARCHAR2(50),
	EMAIL VARCHAR2(50),
	ADDRESS VARCHAR2(1000),
	CLASSNUM NUMBER,
	REG_DATE VARCHAR2(20),
	POSTCODE NUMBER,
	DETAILADDRESS VARCHAR2(1000),
	EXTRAADDRESS VARCHAR2(1000),
	ADMIN NUMBER
);

CREATE SEQUENCE WMEMBER_SEQ START WITH 1;


CREATE TABLE WCLASS (
    CLASSNUM NUMBER(4) NOT NULL PRIMARY KEY,
    CLASSNAME VARCHAR2(1000),
    STU_NUM NUMBER(4),
    STU_REGDATE DATE DEFAULT SYSDATE,
    TOPIC VARCHAR2(2000),
    CONTENT VARCHAR2(3000),
    CLEVEL VARCHAR2(2000),
    UPLOADFILE VARCHAR2(20)
);

CREATE SEQUENCE WCLASS_SEQ START WITH 1;

SELECT * FROM WCLASS;

  


CREATE SEQUENCE WBOARD_SEQ START WITH 1;

DROP SEQUENCE WBOARD_SEQ;
DROP TABLE WBOARD;

CREATE TABLE WBOARD( 
    NUM NUMBER NOT NULL PRIMARY KEY,
    USERID VARCHAR2(50),
    SUBJECT VARCHAR2(200),
    CONTENT VARCHAR2(2000),
    REG_DATE DATE DEFAULT SYSDATE,
    READCOUNT NUMBER,
    CLASSNUM NUMBER,
    FOREIGN KEY (CLASSNUM)
    REFERENCES WCLASS(CLASSNUM) 
    );
SELECT
    *
FROM WBOARD;
    
CREATE TABLE WCOMMENT_BOARD( 
    CNUM NUMBER NOT NULL PRIMARY KEY,
    USERID VARCHAR2(50),
    MSG VARCHAR2(500),
    REG_DATE DATE DEFAULT SYSDATE,
    BNUM NUMBER,
    FOREIGN KEY (BNUM)
    REFERENCES WBOARD(NUM) 
    );
CREATE SEQUENCE WCOMMENT_BOARD_SEQ START WITH 1;

SELECT
    *
FROM WCOMMENT_BOARD;




CREATE SEQUENCE WQNA_SEQ START WITH 1;

DROP SEQUENCE WQNA_SEQ;
DROP TABLE WQNA;
CREATE TABLE WQNA (
    QNUM NUMBER(4) NOT NULL PRIMARY KEY,
    QTITLE VARCHAR2(50),
    USERID VARCHAR2(50),
    QREG_DATE DATE DEFAULT SYSDATE,
    CONTENT VARCHAR2(2000),
    QAvailable NUMBER
);


    
SELECT * FROM wqna;
COMMIT;
    