SELECT TEAM_ID AS 팀ID
,TO_NUMBER (ZIP_CODE1,'999') + TO_NUMBER (ZIP_CODE2, '999') AS 우편번호합
FROM TEAM;

SELECT SYSDATE
FROM DUAL;

SELECT ENAME AS 사원명, HIREDATE AS 입사일자
,TO_NUMBER(TO_CHAR(HIREDATE,'YYYY')) AS 입사년도
,TO_NUMBER(TO_CHAR(HIREDATE,'MM')) AS 입사월
,TO_NUMBER(TO_CHAR(HIREDATE,'DD')) AS 입사일
FROM EMP;

SELECT TO_CHAR (SYSDATE, 'YYYY/MM/DD') AS 날짜
,TO_CHAR (SYSDATE, 'YYYY.MON, DAY') AS 문자형
FROM DUAL;

SELECT TO_CHAR (123456789 / 1200, '$999,999,999.99') AS 환율반영달러
,TO_CHAR (123456789, 'L999,999,999') AS 원화
FROM DUAL;

SELECT ENAME, ROUND (SAL / 12) AS SAL_ROUND, CEIL (SAL / 12) AS SAL_CEIL
FROM EMP;