SELECT MAX (MGR) AS MGR
FROM EMP
WHERE ename = 'JSC';


SELECT NVL (MAX (MGR), 9999) AS MGR
FROM EMP
WHERE ename = 'JSC';

SELECT ENAME, EMPNO, MGR, NULLIF (MGR,7698) AS NUIF
FROM EMP;

SELECT ENAME, COMM, SAL, COALESCE (COMM,SAL) AS COAL
FROM EMP;