SELECT B.TEAM_NAME AS 팀명, A.PLAYER_NAME AS 선수명, A.BACK_NO AS 백넘버
FROM (SELECT TEAM_ID, PLAYER_NAME, BACK_NO FROM PLAYER WHERE POSITION = 'MF') A, TEAM B
WHERE B.TEAM_ID = A.TEAM_ID
ORDER BY 선수명;

SELECT PLAYER_NAME 선수명, POSITION 포지션,
       BACK_NO 백넘버, HEIGHT 키
FROM(SELECT PLAYER_NAME, POSITION, BACK_NO, 
     HEIGHT FROM PLAYER WHERE HEIGHT IS NOT NULL
    ORDER BY HEIGHT DESC)
WHERE ROWNUM <= 5;

SELECT A.TEAM_ID 팀코드, B.TEAM_NAME 팀명, ROUND(AVG(A.HEIGHT), 3) 평균키
FROM PLAYER A, TEAM B
WHERE B.TEAM_ID = A.TEAM_ID
GROUP BY A.TEAM_ID, B.TEAM_NAME
HAVING AVG (A.HEIGHT) < (SELECT AVG(X.HEIGHT)
                        FROM PLAYER X
                        WHERE X.TEAM_ID IN (SELECT TEAM_ID FROM TEAM WHERE TEAM_NAME = '삼성블루윙즈'));
                        
                        
SELECT PLAYER_NAME, POSITION, BACK_NO, TEAM_ID, TEAM_NAME
FROM V_PLAYER_TEAM
WHERE PLAYER_NAME LIKE '황%';

-- 케이리그 소속 선수들 중에서 소속이 삼성블루윙즈 팀인 전남드래곤즈팀인 선수들에 대한 내용 모두 보고싶음
-- 케이리그 소속 선수 중 삼성블루윙즈 팀인 선수들과 전남드래곤즈팀인 선수들의 집합의 집합
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K07';

-- 케이리그 소속 선수들 중에서 소속이 삼성블루윙즈 팀인 선수들과 포지션이 골기퍼인 선수들 모아보기
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'GK';

-- 위의 sql문에서 union all 이라는 집합 연산자를 쓴 경우
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION ALL
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'GK';

SELECT 팀코드, 선수명, 포지션, 백넘버, 키, COUNT(*) AS 중복수
FROM (SELECT TEAM_ID 팀코드, PLAYER_NAME AS 선수명, POSITION AS 포지션, BACK_NO AS 백넘버, HEIGHT AS 키
FROM PLAYER
WHERE TEAM_ID = 'K02'
UNION ALL
SELECT TEAM_ID 팀코드, PLAYER_NAME 선수명, POSITION 포지션, BACK_NO 백넘버, HEIGHT 키
FROM PLAYER
WHERE TEAM_ID = 'GK')
GROUP BY 팀코드, 선수명, 포지션, 백넘버, 키 
HAVING COUNT (*) > 1;